######################################################################
# Automatically generated by qmake (3.1) Thu Aug 27 12:23:10 2026
######################################################################

TEMPLATE = app
TARGET = ProgettoPAO
INCLUDEPATH += .
QT += core
QT += widgets

CONFIG += console

INCLUDEPATH += Logica
INCLUDEPATH += UI

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += Logica/Attivita.h \
           Logica/Lego.h \
           Logica/Musica.h \
           Logica/Sport.h \
           Logica/Videogiochi.h \
           Logica/GestoreAttivita.h \
           Logica/GestoreJson.h \
           Logica/VisitorAttivita.h \
           Logica/VisitorFiltraAttivita.h \
           Logica/VisitorJson.h \
           UI/VisitorSalvaModifica.h \
           UI/MainWindow.h \
           UI/PaginaDettaglio.h \
           UI/PaginaHome.h \
           UI/PaginaCreazioneAttivita.h \
           UI/VisitorModifica.h \
           UI/PaginaModificaAttivita.h
SOURCES += main.cpp \
           Logica/Attivita.cpp \
           Logica/Lego.cpp \
           Logica/Musica.cpp \
           Logica/Sport.cpp \
           Logica/Videogiochi.cpp \
           Logica/GestoreAttivita.cpp \
           Logica/GestoreJson.cpp \
           Logica/VisitorFiltraAttivita.cpp \
           Logica/VisitorJson.cpp \
           UI/VisitorSalvaModifica.cpp \
           UI/MainWindow.cpp \
           UI/PaginaDettaglio.cpp \
           UI/PaginaHome.cpp \
           UI/PaginaCreazioneAttivita.cpp \
           UI/VisitorModifica.cpp \
           UI/PaginaModificaAttivita.cpp
